name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find deployment block
        run: |
          python3 -m src.find_deployment_blocks
      - name: Find daily blocks
        run: |
          python3 -m src.find_daily_blocks
      - name: Process NFT events
        run: |
          python3 -m src.nft_events
      - name: Process Pilot Vault events
        run: |
          python3 -m src.pilot_vault_events
      - name: Process daily states
        run: |
          python3 -m src.daily_states_v2
      - name: Process daily points
        run: |
          python3 -m src.daily_points_v2
      - name: Aggregate daily points
        run: |
          python3 -m src.aggregate_daily_points
      - name: Run all tests
        run: |
         python3 test/main_test.py
          