name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find deployment block
        run: |
          python3 src/find_deployment_blocks.py
      - name: Find daily blocks
        run: |
          python3 src/find_daily_blocks.py
      - name: Process NFT events
        run: |
          python3 src/nft_events.py
      - name: Process Pilot Vault events
        run: |
          python3 src/pilot_vault_events.py
      - name: Process daily states
        run: |
          python3 src/daily_states_v2.py
      - name: Process daily points
        run: |
          python3 src/daily_points_v2.py
      - name: Aggregate daily points
        run: |
          python3 src/aggregate_daily_points.py
      - name: Run all tests
        run: |
         python3 test/main_test.py
          